//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.IO;
using System.Xml;
using System.Xml.Serialization;


public static class XmlIO
{
	public static object Load( string path, Type type )
	{
		object thing = null;

		XmlTextReader reader = new XmlTextReader( path );
		XmlSerializer serializer = new  XmlSerializer( type );
		thing = serializer.Deserialize( reader );
		reader.Close();

		return( thing );
	}

	public static void Save( object thing, string path )
	{
		XmlTextWriter writer = new XmlTextWriter( path, Encoding.ASCII );
		writer.Formatting = Formatting.Indented;
		XmlSerializer serializer = new XmlSerializer( thing.GetType() );
		serializer.Serialize( writer, thing );
		writer.Close();
	}
}


